# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EazyoApp' do
  pod 'AppCenter/Push', '~> 1.13.0'
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EazyoApp

  

  platform :ios, '9.0'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'EazyoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EazyoApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EazyoApp-tvOS

  target 'EazyoApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
